package com.sdk.ipassplussdk.utils

enum class Errors {
    INVALID_KEY, WRONG_API_SPECIFIER, EMPTY_X_API_KEY, API_URL_NOT_FOUND, EMAIL_EMPTY, FNAME_EMPTY, LNAME_EMPTY, MEMBERSHIPID_EMPTY, DOB_EMPTY, GENDER_EMPTY, HEALTH_CON_EMPTY, CUS_FIELDS_EMPTY, INVALID_EMAIL_FROMAT, HEALTH_METRIC_EMPTY, EMAILNOT_UNIQUE
}
